### ISSUE TITLE
have a bug

### ISSUE THREAD

**Issue by mskgroup** [nesrak1/TypeTreeDumpToTpk#1]
I need to manually change the file name from "3.4.0.json" changed to "3.4.0f0.json", until 4.7.2

error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\3.4.2f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\3.4.2f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\3.5.7f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\3.5.7f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.0.1f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.0.1f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.1.5f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.1.5f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.2.2f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.2.2f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.3.4f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.3.4f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.5.5f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.5.5f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.6.9f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.6.9f0.json'.
error converting d:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.7.2f0.json:
Could not find file 'd:\typetreedumptotpk\typetreedumps\typetreedumps-main\InfoJson\4.7.2f0.json'.

**Comment by nesrak1** [comment]
Should be fixed now.
